"""The self-distillation pool: generated, because no corpus can supply it.

WHY IT CANNOT BE SOURCED. The self-distill pool needs tasks the being solves SLOWLY -- not
instantly from a fact, but by composing over his own memory. That is a property of the
BEING'S CURRENT STATE, not of a problem in isolation, so no public corpus has it. Measured,
twice: CodeContests supplied 149 screened survivors and exactly 0 self-distill survivors,
because competitive problems are too hard to be "solvable but slow".

THE FOUR PIECES, and each is load-bearing:

  1. SEED from keys he already solves via `system2_local`.
  2. ASK for a DIFFERENT problem, same shape, similar difficulty, different specifics -- not a
     rephrasing of the seed, which would test the same instant the same instant.
  3. VERIFY the oracle's own reference solution in the sandbox BEFORE anything is admitted. A
     generated task is not more trustworthy than a public one for having been custom-made.
  4. THREE-WAY FILTER, which is the whole point:
        solves instantly via system1  -> already known, DISCARD
        fails entirely (oracle and facts off) -> too hard, ROUTE TO THE SCREENED POOL
        resolves via system2_local    -> KEEP

    python tools/make_generated_pool.py --pilot 12
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

OUT = ROOT / "state" / "curriculum"
LICENCE = "generated by the oracle, verified by execution"


def _oracle():
    from organs.api_oracle import oracle_from_config
    cfg = json.loads((ROOT / "config" / "hybrid_config.json").read_text(encoding="utf-8"))
    return oracle_from_config(cfg)


def _agent():
    from tools.knowledge_run import _agent as kagent
    return kagent()


def seeds(rows, limit: int) -> list:
    """Tasks he solves by composition RIGHT NOW -- the only valid seeds.

    Anything he solves instantly is already compiled; anything he cannot solve has nothing
    to vary.
    """
    from tools.curriculum_run import _loop_agent
    from organs.harness import Harness
    from organs.concepts import extract_key
    agent = _loop_agent()
    loop = agent.reasoning_loop
    h = Harness(loop=loop, solver=loop.solver, sandbox=loop.sandbox,
                learning=getattr(agent, "learning_loop", None), channel=None)
    out = []
    for r in rows:
        if len(out) >= limit:
            break
        res = h.solve(r["task"], r["check"], learn=False, oracle=False)
        if res.get("solved") and res.get("branch") == "system2_local":
            c, s, sh = extract_key(r["task"], r["check"])
            out.append({"task": r["task"], "check": r["check"], "key": [c, s, sh]})
    return out


_PROMPT = """You are writing a NEW coding exercise.

Here is an exercise the student can already solve:

TASK: %s

ITS ASSERTIONS:
%s

Write a DIFFERENT exercise of the same SHAPE and similar difficulty. It must:
- test the same KIND of reasoning, but with different specifics (different objects, values, wording),
- NOT be a rephrasing of the exercise above,
- be stated in one sentence, in the same style as TASK,
- come with Python assertions in the same form as ITS ASSERTIONS, calling ONE function.

Reply with JSON only, exactly:
{"task": "<one sentence>", "check": "<assert lines>", "solution": "<a complete function definition that satisfies the assertions>"}
"""


def generate(oracle, seed: dict, tries: int = 2, diag: dict | None = None) -> dict | None:
    """One candidate: a task, its assertions, and the oracle's own reference solution.

    `diag` collects WHY a call produced nothing. Without it the scale run reported five
    consecutive `empty`s and stopped, and the reason -- `task_budget_exceeded`, from a missing
    `start_task()` -- was unrecoverable from the report. A stop signal that cannot say what it
    saw is a stop signal that will be misread as provider degradation, which is exactly what
    happened here.
    """
    prompt = _PROMPT % (seed["task"], seed["check"])
    for attempt in range(tries):
        # EACH CANDIDATE IS ITS OWN TASK. `Budget.task_spent` accumulates until this clears
        # it, so without this call every candidate was billed against the first one's 4000
        # token ceiling -- roughly ten candidates, then a wall of `task_budget_exceeded` that
        # the clustering guard correctly read as a broken oracle. Same defect as the probe's
        # (15 of 20 empty) and knowledge.py's (15 of 15 refused).
        try:
            oracle.budget.start_task()
        except Exception:
            pass
        try:
            res = oracle.query(prompt, max_tokens=700, temperature=0.3,
                               purpose="generated_task", no_reasoning=True)
        except Exception as exc:
            if diag is not None:
                diag["reason"] = "%s: %s" % (type(exc).__name__, str(exc)[:70])
            return None
        text = str(res.get("text") or "")
        if diag is not None:
            diag["reason"] = str(res.get("reason") or res.get("finish_reason") or
                                 ("ok" if text else "empty_text"))[:90]
        m = re.search(r"\{.*\}", text, re.S)
        if not m:
            continue
        try:
            data = json.loads(m.group(0))
        except ValueError:
            continue
        task = str(data.get("task") or "").strip()
        check = str(data.get("check") or "").strip()
        sol = str(data.get("solution") or "").strip()
        if task and "assert" in check and "def " in sol:
            return {"task": task, "check": check, "gold": sol}
    return None


def verify(agent, task: str, check: str, gold: str) -> bool:
    """The same execution bar as every public corpus: run it, don't assume it.

    THE CHECK MUST BE APPENDED. `_verify_detail(code, task)` runs `code` ALONE -- and when
    that code merely defines functions and exits 0 it returns (True, "definitional"), so
    passing the gold by itself reports every solution as correct. Measured with a battery of
    deliberately wrong solutions: constant, first argument, and `return None` all came back
    accepted. The first pilot's "verified 10 of 10" was therefore a vacuous zero, and it took
    a separate battery to notice. The real callers build `code + "\n\n" + check`; so does this.
    """
    from organs.harness import Harness
    loop = agent.reasoning_loop
    if loop.solver.sandbox is None:
        return False
    ok, _kind = loop.solver._verify_detail(gold + "\n\n" + str(check), check)
    return bool(ok)


def classify(agent, task: str, check: str) -> str:
    """The three-way filter. One of: known, too_hard, self_distill."""
    from organs.harness import Harness
    loop = agent.reasoning_loop
    h = Harness(loop=loop, solver=loop.solver, sandbox=loop.sandbox,
                learning=getattr(agent, "learning_loop", None), channel=None)
    # 1. already known?  System 1 answers from a filed fact or a recalled procedure.
    fact = h._fact(task, check)
    if fact.get("found"):
        ok, _ = loop._attempt({"code": fact["code"], "label": "fact:probe"}, check)
        if ok:
            return "known"
    out = h.solve(task, check, learn=False, oracle=False)
    if out.get("solved"):
        branch = str(out.get("branch"))
        if branch == "system1_fact" or branch == "system1_recall":
            return "known"
        if branch == "system2_local":
            return "self_distill"
        return "known"
    return "too_hard"


def pilot(n: int = 12, seed_limit: int = 40) -> dict:
    from tools.make_curriculum import load
    agent = _agent()
    oracle = getattr(agent, "api_oracle", None)
    if oracle is None or not getattr(oracle, "has_key", False):
        return {"error": "no oracle key"}
    rows = load("holdout") + load("train")
    sds = seeds(rows, seed_limit)
    # `seeds()` builds a TOOL agent, and `_loop_agent` does
    # `os.environ.setdefault("HYBRIDLLM_OFFLINE", "1")` -- which RE-ARMS the fence that
    # `_agent()` had popped a moment earlier. The fence is read at CALL time, not at import,
    # so every generation below would have come back `offline_mode`... while the report said
    # `generated: 0`, which reads like a model that produced nothing. It produced nothing
    # because it was never asked. Pop it again, after the seeding, every time.
    os.environ.pop("HYBRIDLLM_OFFLINE", None)
    report = {"seeds_found": len(sds), "attempted": 0, "generated": 0,
              "verification_failed": 0, "known": 0, "too_hard": 0, "self_distill": 0}
    kept, routed = [], []
    for seed in sds:
        if report["attempted"] >= n:
            break
        report["attempted"] += 1
        cand = generate(oracle, seed)
        if not cand:
            continue
        report["generated"] += 1
        if not verify(agent, cand["task"], cand["check"], cand["gold"]):
            report["verification_failed"] += 1
            continue
        bucket = classify(agent, cand["task"], cand["check"])
        report[bucket] = report.get(bucket, 0) + 1
        rec = dict(cand)
        rec["id"] = "gen:" + hashlib.sha256(cand["task"].encode()).hexdigest()[:10]
        rec["source"] = "generated"
        rec["licence"] = LICENCE
        rec["seed_key"] = seed["key"]
        rec["bucket"] = bucket
        rec["split"] = "train"
        (kept if bucket == "self_distill" else routed).append(rec)
    report["seed_keys"] = [s["key"] for s in sds[:n]]
    if kept:
        p = OUT / "generated_selfdistill.jsonl"
        p.write_text("\n".join(json.dumps(r) for r in kept), encoding="utf-8")
        report["self_distill_path"] = str(p)
    if routed:
        p = OUT / "generated_screened.jsonl"
        p.write_text("\n".join(json.dumps(r) for r in routed), encoding="utf-8")
        report["screened_path"] = str(p)
    return report


def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", str(text).lower())


def existing_texts() -> set:
    """Everything already in a corpus. A generated task must not duplicate one of these."""
    from tools.make_curriculum import load
    out = set()
    for src in ("holdout", "train", "mbpp_all", "codecontests"):
        try:
            for r in load(src):
                out.add(_norm(r.get("task", "")))
        except Exception:
            pass
    return out


def distribution(rows) -> dict:
    """The (concept, subject, shape) histogram.

    An ALTERNATING split needs concepts that RECUR, because a concept seen once has nothing
    to transfer to; so the count of keys and the count of repeat keys both matter and the
    histogram has to be reported, not summarised into one number.
    """
    from collections import Counter
    from organs.concepts import extract_key
    hist = Counter()
    for r in rows:
        try:
            hist[tuple(extract_key(r["task"], r["check"]))] += 1
        except Exception:
            hist[("unknown", "unknown", "unknown")] += 1
    return {"histogram": {"%s|%s|%s" % k: v for k, v in hist.most_common()},
            "distinct_keys": len(hist),
            "keys_with_repeats": sum(1 for v in hist.values() if v > 1),
            "max_repeat": max(hist.values()) if hist else 0}


def _load(path: Path) -> list:
    if not path.exists():
        return []
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            try:
                out.append(json.loads(line))
            except Exception:
                pass
    return out


def scale(target_self: int = 100, target_screened: int = 100,
          max_attempts: int = 400, seed_limit: int = 250,
          append: bool = True) -> dict:
    """Generate until both buckets are full, watching the oracle for degradation.

    STOPS RATHER THAN PUSHING THROUGH A DEGRADED ORACLE. If empty completions or refusals
    start clustering, the run ends and says so -- whether to throttle or pay for more quota
    is a decision for the human, and it is not made here by quietly retrying.
    """
    from organs.api_oracle import oracle_open
    from tools.make_curriculum import load
    from organs.concepts import extract_key

    with oracle_open():
        agent = _agent()
        os.environ.pop("HYBRIDLLM_OFFLINE", None)
        oracle = getattr(agent, "api_oracle", None)
        if oracle is None or not getattr(oracle, "has_key", False):
            return {"error": "no oracle key"}
        rows = load("holdout") + load("train")
        sds = seeds(rows, seed_limit)
        os.environ.pop("HYBRIDLLM_OFFLINE", None)
        if not sds:
            return {"error": "no self_distill seeds found"}

        known = existing_texts()
        seen = set()
        kept, routed = [], []
        # APPEND, DO NOT OVERWRITE. `_write` replaces the file wholesale, so a top-up run
        # would have destroyed the pool while an experiment was reading it. The existing rows
        # are loaded first, their texts seeded into the duplicate filter, and the union is
        # written back -- so a top-up adds material and can never remove it.
        if append:
            kept = _load(OUT / "generated_selfdistill.jsonl")
            routed = _load(OUT / "generated_screened.jsonl")
        for r in kept + routed:
            seen.add(_norm(r.get("task", "")))
        rep = {"attempted": 0, "generated": 0, "duplicate": 0,
               "existing_self_distill": len(kept), "existing_screened": len(routed),
               "verification_failed": 0, "empty": 0, "known": 0, "too_hard": 0,
               "self_distill": 0, "stopped": None, "oracle_empties_recent": []}
        empties = 0
        i = 0
        while (len(kept) < target_self or len(routed) < target_screened) \
                and rep["attempted"] < max_attempts:
            seed = sds[i % len(sds)]
            i += 1
            rep["attempted"] += 1
            diag: dict = {}
            cand = generate(oracle, seed, diag=diag)
            if not cand:
                rep["empty"] += 1
                empties += 1
                rep["oracle_empties_recent"].append(
                    {"attempt": rep["attempted"], "reason": diag.get("reason")})
                # CLUSTERING IS THE STOP SIGNAL, and it now carries the reason for each
                # failure so the report can distinguish a spent budget from a dead provider.
                if empties >= 5:
                    rep["stopped"] = ("oracle returned %d empty completions in a row at "
                                      "attempt %d: %s"
                                      % (empties, rep["attempted"],
                                         diag.get("reason")))
                    break
                continue
            empties = 0
            rep["generated"] += 1
            key = _norm(cand["task"])
            if key in known or key in seen:
                rep["duplicate"] += 1
                continue
            if not verify(agent, cand["task"], cand["check"], cand["gold"]):
                rep["verification_failed"] += 1
                continue
            bucket = classify(agent, cand["task"], cand["check"])
            rec = dict(cand)
            rec["id"] = "gen:" + hashlib.sha256(cand["task"].encode()).hexdigest()[:10]
            rec["source"] = "generated"
            rec["licence"] = LICENCE
            rec["seed_key"] = seed["key"]
            rec["bucket"] = bucket
            rec["split"] = "train"
            if bucket == "known":
                rep["known"] += 1
                continue
            seen.add(key)
            if bucket == "self_distill" and len(kept) < target_self:
                kept.append(rec)
                rep["self_distill"] += 1
            elif target_screened and len(routed) < target_screened:
                routed.append(rec)
                rep[bucket] = rep.get(bucket, 0) + 1
            # Write as we go: a run that dies at hour two must not lose hour one.
            _write(OUT / "generated_selfdistill.jsonl", kept)
            _write(OUT / "generated_screened.jsonl", routed)
        rep["self_distill_final"] = len(kept)
        rep["screened_final"] = len(routed)
        rep["distribution_self_distill"] = distribution(kept)
        rep["distribution_screened"] = distribution(routed)
    return rep


def _write(path: Path, rows: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(json.dumps(r) for r in rows), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pilot", type=int, default=12)
    ap.add_argument("--seeds", type=int, default=40)
    ap.add_argument("--scale", type=int, default=0,
                    help="generate this many of each bucket")
    ap.add_argument("--scale-self", type=int, default=0,
                    help="top up ONLY the self_distill bucket to this size, appending")
    ap.add_argument("--max-attempts", type=int, default=400)
    a = ap.parse_args()
    if a.scale_self:
        rep = scale(target_self=a.scale_self, target_screened=0,
                    max_attempts=a.max_attempts, append=True)
        Path("state/generator_topup.json").write_text(json.dumps(rep, indent=1),
                                                      encoding="utf-8")
        print(json.dumps(rep, indent=1))
        return 0
    if a.scale:
        rep = scale(target_self=a.scale, target_screened=a.scale,
                    max_attempts=a.max_attempts)
        Path("state/generator_scale.json").write_text(json.dumps(rep, indent=1),
                                                     encoding="utf-8")
        print(json.dumps(rep, indent=1))
        return 0
    print(json.dumps(pilot(a.pilot, a.seeds), indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
