"""The self-distillation pool: generated, because no corpus can supply it.

WHY IT CANNOT BE SOURCED. The self-distill pool needs tasks the being solves SLOWLY -- not
instantly from a fact, but by composing over his own memory. That is a property of the
BEING'S CURRENT STATE, not of a problem in isolation, so no public corpus has it. Measured,
twice: CodeContests supplied 149 screened survivors and exactly 0 self-distill survivors,
because competitive problems are too hard to be "solvable but slow".

THE FOUR PIECES, and each is load-bearing:

  1. SEED from keys he already solves via `system2_local`.
  2. ASK for a DIFFERENT problem, same shape, similar difficulty, different specifics -- not a
     rephrasing of the seed, which would test the same instant the same instant.
  3. VERIFY the oracle's own reference solution in the sandbox BEFORE anything is admitted. A
     generated task is not more trustworthy than a public one for having been custom-made.
  4. THREE-WAY FILTER, which is the whole point:
        solves instantly via system1  -> already known, DISCARD
        fails entirely (oracle and facts off) -> too hard, ROUTE TO THE SCREENED POOL
        resolves via system2_local    -> KEEP

    python tools/make_generated_pool.py --pilot 12
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

OUT = ROOT / "state" / "curriculum"
LICENCE = "generated by the oracle, verified by execution"


def _oracle():
    from organs.api_oracle import oracle_from_config
    cfg = json.loads((ROOT / "config" / "hybrid_config.json").read_text(encoding="utf-8"))
    return oracle_from_config(cfg)


def _agent():
    from tools.knowledge_run import _agent as kagent
    return kagent()


def seeds(rows, limit: int) -> list:
    """Tasks he solves by composition RIGHT NOW -- the only valid seeds.

    Anything he solves instantly is already compiled; anything he cannot solve has nothing
    to vary.
    """
    from tools.curriculum_run import _loop_agent
    from organs.harness import Harness
    from organs.concepts import extract_key
    agent = _loop_agent()
    loop = agent.reasoning_loop
    h = Harness(loop=loop, solver=loop.solver, sandbox=loop.sandbox,
                learning=getattr(agent, "learning_loop", None), channel=None)
    out = []
    for r in rows:
        if len(out) >= limit:
            break
        res = h.solve(r["task"], r["check"], learn=False, oracle=False)
        if res.get("solved") and res.get("branch") == "system2_local":
            c, s, sh = extract_key(r["task"], r["check"])
            out.append({"task": r["task"], "check": r["check"], "key": [c, s, sh]})
    return out


_PROMPT = """You are writing a NEW coding exercise.

Here is an exercise the student can already solve:

TASK: %s

ITS ASSERTIONS:
%s

Write a DIFFERENT exercise of the same SHAPE and similar difficulty. It must:
- test the same KIND of reasoning, but with different specifics (different objects, values, wording),
- NOT be a rephrasing of the exercise above,
- be stated in one sentence, in the same style as TASK,
- come with Python assertions in the same form as ITS ASSERTIONS, calling ONE function.

Reply with JSON only, exactly:
{"task": "<one sentence>", "check": "<assert lines>", "solution": "<a complete function definition that satisfies the assertions>"}
"""


def generate(oracle, seed: dict, tries: int = 2) -> dict | None:
    """One candidate: a task, its assertions, and the oracle's own reference solution."""
    prompt = _PROMPT % (seed["task"], seed["check"])
    for attempt in range(tries):
        try:
            res = oracle.query(prompt, max_tokens=700, temperature=0.3,
                               purpose="generated_task", no_reasoning=True)
        except Exception:
            return None
        text = str(res.get("text") or "")
        m = re.search(r"\{.*\}", text, re.S)
        if not m:
            continue
        try:
            data = json.loads(m.group(0))
        except ValueError:
            continue
        task = str(data.get("task") or "").strip()
        check = str(data.get("check") or "").strip()
        sol = str(data.get("solution") or "").strip()
        if task and "assert" in check and "def " in sol:
            return {"task": task, "check": check, "gold": sol}
    return None


def verify(agent, task: str, check: str, gold: str) -> bool:
    """The same execution bar as every public corpus: run it, don't assume it."""
    from organs.harness import Harness
    loop = agent.reasoning_loop
    if loop.solver.sandbox is None:
        return False
    ok, _kind = loop.solver._verify_detail(gold, check)
    return bool(ok)


def classify(agent, task: str, check: str) -> str:
    """The three-way filter. One of: known, too_hard, self_distill."""
    from organs.harness import Harness
    loop = agent.reasoning_loop
    h = Harness(loop=loop, solver=loop.solver, sandbox=loop.sandbox,
                learning=getattr(agent, "learning_loop", None), channel=None)
    # 1. already known?  System 1 answers from a filed fact or a recalled procedure.
    fact = h._fact(task, check)
    if fact.get("found"):
        ok, _ = loop._attempt({"code": fact["code"], "label": "fact:probe"}, check)
        if ok:
            return "known"
    out = h.solve(task, check, learn=False, oracle=False)
    if out.get("solved"):
        branch = str(out.get("branch"))
        if branch == "system1_fact" or branch == "system1_recall":
            return "known"
        if branch == "system2_local":
            return "self_distill"
        return "known"
    return "too_hard"


def pilot(n: int = 12, seed_limit: int = 40) -> dict:
    from tools.make_curriculum import load
    agent = _agent()
    oracle = getattr(agent, "api_oracle", None)
    if oracle is None or not getattr(oracle, "has_key", False):
        return {"error": "no oracle key"}
    rows = load("holdout") + load("train")
    sds = seeds(rows, seed_limit)
    # `seeds()` builds a TOOL agent, and `_loop_agent` does
    # `os.environ.setdefault("HYBRIDLLM_OFFLINE", "1")` -- which RE-ARMS the fence that
    # `_agent()` had popped a moment earlier. The fence is read at CALL time, not at import,
    # so every generation below would have come back `offline_mode`... while the report said
    # `generated: 0`, which reads like a model that produced nothing. It produced nothing
    # because it was never asked. Pop it again, after the seeding, every time.
    os.environ.pop("HYBRIDLLM_OFFLINE", None)
    report = {"seeds_found": len(sds), "attempted": 0, "generated": 0,
              "verification_failed": 0, "known": 0, "too_hard": 0, "self_distill": 0}
    kept, routed = [], []
    for seed in sds:
        if report["attempted"] >= n:
            break
        report["attempted"] += 1
        cand = generate(oracle, seed)
        if not cand:
            continue
        report["generated"] += 1
        if not verify(agent, cand["task"], cand["check"], cand["gold"]):
            report["verification_failed"] += 1
            continue
        bucket = classify(agent, cand["task"], cand["check"])
        report[bucket] = report.get(bucket, 0) + 1
        rec = dict(cand)
        rec["id"] = "gen:" + hashlib.sha256(cand["task"].encode()).hexdigest()[:10]
        rec["source"] = "generated"
        rec["licence"] = LICENCE
        rec["seed_key"] = seed["key"]
        rec["bucket"] = bucket
        rec["split"] = "train"
        (kept if bucket == "self_distill" else routed).append(rec)
    report["seed_keys"] = [s["key"] for s in sds[:n]]
    if kept:
        p = OUT / "generated_selfdistill.jsonl"
        p.write_text("\n".join(json.dumps(r) for r in kept), encoding="utf-8")
        report["self_distill_path"] = str(p)
    if routed:
        p = OUT / "generated_screened.jsonl"
        p.write_text("\n".join(json.dumps(r) for r in routed), encoding="utf-8")
        report["screened_path"] = str(p)
    return report


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pilot", type=int, default=12)
    ap.add_argument("--seeds", type=int, default=40)
    a = ap.parse_args()
    print(json.dumps(pilot(a.pilot, a.seeds), indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
